
name: AGENT_BIBLE.md Compliance Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  compliance-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Run AGENT_BIBLE.md Compliance Check
      run: |
        python agent_bible_compliance_test.py
    
    - name: Check for AGENT_BIBLE.md updates
      run: |
        if git diff --name-only HEAD~1 | grep -q "AGENT_BIBLE.md"; then
          echo "⚠️ AGENT_BIBLE.md was modified - ensure all agent logic is updated accordingly"
          echo "agent_bible_modified=true" >> $GITHUB_ENV
        fi
    
    - name: Validate API endpoints
      run: |
        if python -c "import main; print('Flask app imports successfully')"; then
          echo "✅ Flask app structure valid"
        else
          echo "❌ Flask app import failed"
          exit 1
        fi
